### ISSUE TITLE
Adicionar Descrição do Teste de listarInconformidadesDeProfessores

### ISSUE THREAD

**Issue by 0xLuz** [teste-sw/distribuicao_de_disciplinas#1]
**Equipe: Adolfo, Joabe e Pedro**
# Pré-condições

Ter lista de professores vinculados à distribuição
# Pós-condições

Lista de inconformidades
**Classe:**

`Inconformidade`

**Atributos:**

```
Professor professor;
int disparidade; // (quantidade de horas acima ou abaixo do ideal para aquele professor)
```

---
## Classes de valores do domínio de entrada

Considerando a lista de com professores a serem verificados

**Valores válidos** 
lista de professores > 0
**Valores inválidos** 
lista de professores vazia → throws NaoHaProfessoresNaDistribuicao
lista de professores nula → throws ListaDeProfessoresNula
## Considerando a inconformidade de cada professor dentro da lista

precisamos da jornada de trabalho e do tipo de contrato do professor (40h, 20h, DE)
## Professor DE e 40h

**Valores válidos** 
14h
**Valores inválidos**
CH> 14h
CH< 14h
## Professor 20h

*\* Valores válidos *\* 
11h
*\* Valores inválidos*\* 
CH > 11h
CH< 11h

---
# Pseudocode dos teste(s):
### Teste 1:  Vericar se função com lista vazia retorna exception NaoHaProfessoresNaDistribuicao.

```
1 - Chamar função listarInconformidadesDeProfessores de incocom lista vazia.
2 - Verificar se é verdade que a função respondeu com NaoHaProfessoresNaDistribuicao.
```
### Test 2: Vericar se função com lista nula retorna exception ListaDeProfessoresNula.

```
1 - Chamar função _listarInconformidadesDeProfessores_ de incocom lista nula. 
2 -  Verificar se é verdade que a função respondeu com ListaDeProfessoresNula. 
```
### Test 3: Verificar se cada professor retornado na função possui a inconformidades definidas.

**Inconformidade 1 (IN1):**   Ser professor de 20hs e tem menos ou mais do que 11hs de carga horária.
**Inconformidade 2 (IN2):** Ser professor de 40hs e tem menos ou mais do que 14hs de carga horária.

```
1 - Verificar se IN1 é verdade para cada um dos elementos professores da lista retornada pela função listarInconformidadesDeProfessores.
2 - Verificar se IN2 é verdade para cada um dos elementos professores da lista retornada pela função listarInconformidadesDeProfessores.
```

**Comment by leonardo-minora** [comment]
No caso de Teste 3 Inclua o tipo DE para a validação.

**Comment by leonardo-minora** [comment]
Já inclui no wiki do projeto
